[project]
name = "breakthrough-erc4626-analyzer"
authors = ["Breakthrough Technologies"]
description = "A comprehensive ERC4626 vault performance analyzer with advanced yield mechanisms"
telemetry = false
requirements = []
[contracts.erc4626-vault-analyzer]
path = "contracts/erc4626-vault-analyzer.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
